[workspace]
authors = ["Motro <motro@email>"]
channels = ["conda-forge","bioconda"]
name = "MST"
platforms = ["linux-64"]
version = "0.1.0"

# Default system requirements for Linux
[system-requirements]
linux = "4.18"
libc = { family = "glibc", version = "2.28" }

[tasks]

[dependencies]
pygraphviz = "*"
genomic_address_service = "*"
scikit-learn = "*"
cgmlst-dists = "*"
cairo = ">=1.18.4,<2"

[pypi-dependencies]
pandas = "*"
numpy = "*"
numba = "*"
matplotlib = "*"
networkx = "*"
bottleneck = "==1.4.0"
argparse = "*"