[workspace]
authors = ["Yair <yair@mail.com>"]
channels = ["conda-forge","bioconda"]
name = "bam_cov"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
minimap2 = ">=2.29,<3"
samtools = ">=1.21,<2"
vega-lite-cli = ">=6.1.0,<7"
alignoth = ">=0.14.3,<0.15"
